Repository ironcore-dev/ironcore, pull requests merged in 2022-12, with the labels that each got.

#558 Implement `NATGateway` controller
  config/controller/rbac/role.yaml
  onmetal-controller-manager/client/client.go
  onmetal-controller-manager/controllers/networking/events/events.go
  onmetal-controller-manager/controllers/networking/natgateway_controller.go
  onmetal-controller-manager/controllers/networking/natgateway_controller_test.go
  onmetal-controller-manager/controllers/networking/suite_test.go
  onmetal-controller-manager/main.go
Labels: size/XL

#574 Add & populate `AliasPrefixRouting.NetworkRef`
  api/networking/v1alpha1/aliasprefixrouting_type.go
  api/networking/v1alpha1/zz_generated.deepcopy.go
  broker/machinebroker/server/server_suite_test.go
  client-go/applyconfigurations/internal/internal.go
  client-go/applyconfigurations/networking/v1alpha1/aliasprefixrouting.go
  client-go/openapi/zz_generated.openapi.go
  onmetal-apiserver/internal/apis/networking/aliasprefixrouting_type.go
  onmetal-apiserver/internal/apis/networking/v1alpha1/zz_generated.conversion.go
  onmetal-apiserver/internal/apis/networking/zz_generated.deepcopy.go
  onmetal-controller-manager/clientutils/clientutils.go
  onmetal-controller-manager/controllers/networking/aliasprefix_controller.go
  onmetal-controller-manager/controllers/networking/aliasprefix_controller_test.go
  onmetal-controller-manager/controllers/networking/suite_test.go
  onmetal-controller-manager/main.go
Labels: bug, enhancement, size/L

#566 Implement field selectors for `poolRef` attributes
  .golangci.yaml
  api/compute/v1alpha1/common.go
  api/storage/v1alpha1/common.go
  onmetal-apiserver/internal/apis/compute/common.go
  onmetal-apiserver/internal/apis/compute/v1alpha1/conversions.go
  onmetal-apiserver/internal/apis/compute/v1alpha1/register.go
  onmetal-apiserver/internal/apis/storage/common.go
  onmetal-apiserver/internal/apis/storage/v1alpha1/conversions.go
  onmetal-apiserver/internal/apis/storage/v1alpha1/register.go
  onmetal-apiserver/internal/app/app_test.go
  onmetal-apiserver/internal/registry/compute/machine/storage/storage.go
  onmetal-apiserver/internal/registry/compute/machine/strategy.go
  onmetal-apiserver/internal/registry/storage/volume/storage/storage.go
  onmetal-apiserver/internal/registry/storage/volume/strategy.go
Labels: enhancement, size/L

#589 Fix the `VolumePoolState`
  api/storage/v1alpha1/volumepool_types.go
  onmetal-apiserver/internal/apis/storage/volumepool_types.go
Labels: bug, size/S

#591 Implement ori load balancers
  broker/machinebroker/aliasprefixes/aliasprefixes.go
  broker/machinebroker/api/v1alpha1/common_types.go
  broker/machinebroker/apiutils/apiutils.go
  broker/machinebroker/loadbalancers/loadbalancers.go
  broker/machinebroker/server/common.go
  broker/machinebroker/server/networkinterface.go
  broker/machinebroker/server/networkinterface_create.go
  broker/machinebroker/server/networkinterface_create_test.go
  broker/machinebroker/server/networkinterface_list.go
  broker/machinebroker/server/server.go
  ori/apis/machine/v1alpha1/api.pb.go
  ori/apis/machine/v1alpha1/api.proto
Labels: enhancement, size/XXL

#588 Object Storage Proposal
  docs/proposals/05-object-storage.md
Labels: documentation, size/L

#594 Reconcile load balancers in machinepoollet
  broker/machinebroker/aliasprefixes/aliasprefixes.go
  broker/machinebroker/api/v1alpha1/common_types.go
  broker/machinebroker/apiutils/apiutils.go
  broker/machinebroker/apiutils/conversion.go
  broker/machinebroker/loadbalancers/loadbalancers.go
  broker/machinebroker/server/common.go
  broker/machinebroker/server/networkinterface_create.go
  broker/machinebroker/server/networkinterface_create_loadbalancer.go
  broker/machinebroker/server/networkinterface_create_loadbalancer_test.go
  broker/machinebroker/server/networkinterface_create_test.go
  broker/machinebroker/server/networkinterface_delete.go
  broker/machinebroker/server/networkinterface_delete_loadbalancer.go
  broker/machinebroker/server/networkinterface_list.go
  go.mod
  go.sum
  ori/apis/machine/machine.go
  ori/apis/machine/v1alpha1/api.pb.go
  ori/apis/machine/v1alpha1/api.proto
  ori/apis/machine/v1alpha1/utils.go
  ori/remote/machine/runtime.go
  ori/testing/machine/fake.go
  poollet/machinepoollet/client/client.go
  poollet/machinepoollet/cmd/machinepoollet/app/app.go
  poollet/machinepoollet/controllers/controllers_suite_test.go
  poollet/machinepoollet/controllers/machine_controller_networkinterface.go
  poollet/machinepoollet/controllers/machine_controller_test.go
  utils/maps/maps.go
  utils/slices/slices.go
Labels: enhancement, size/XXL
