Repository ironcore-dev/ironcore, pull requests merged in 2022-11, with the labels that each got.

#526 Fix device name generation in case of new volumes
  admission/plugin/machinevolumedevices/admission.go
  admission/plugin/machinevolumedevices/admission_test.go
Labels: bug, enhancement, size/L

#518 Loadbalancer and NAT-Gateway Proposal
  docs/proposals/01-networking-integration.md
  docs/proposals/03-loadbalancer.md
  docs/proposals/04-nat-gateway.md
Labels: documentation, size/L

#531 Fix typo in test
  apis/storage/validation/volumepool_test.go
Labels: bug, storage, api-change, size/XS

#530 Extend `Network` with `spec.providerID` & `status.state`
  apis/networking/network_type.go
  apis/networking/v1alpha1/network_type.go
  apis/networking/v1alpha1/zz_generated.conversion.go
  apis/networking/v1alpha1/zz_generated.deepcopy.go
  apis/networking/validation/network.go
  apis/networking/validation/network_test.go
  apis/networking/zz_generated.deepcopy.go
  config/samples/networking_v1alpha1_network.yaml
  generated/clientset/internalversion/typed/networking/internalversion/fake/fake_network.go
  generated/clientset/internalversion/typed/networking/internalversion/network.go
  generated/clientset/versioned/typed/networking/v1alpha1/fake/fake_network.go
  generated/clientset/versioned/typed/networking/v1alpha1/network.go
  generated/openapi/zz_generated.openapi.go
  onmetal-apiserver/registry/networking/network/storage/tableconvertor.go
  onmetal-apiserver/registry/networking/network/strategy.go
  onmetal-apiserver/registry/networking/rest/rest.go
Labels: api-change, size/L, networking

#532 Implement `machinebroker` / API updates / `ori` updates
  apis/compute/machine_types.go
  apis/compute/v1alpha1/machine_types.go
  apis/compute/v1alpha1/zz_generated.conversion.go
  apis/compute/v1alpha1/zz_generated.deepcopy.go
  apis/compute/zz_generated.deepcopy.go
  apis/networking/networkinterface_types.go
  apis/networking/v1alpha1/networkinterface_types.go
  apis/networking/v1alpha1/zz_generated.conversion.go
  apis/storage/v1alpha1/volume_types.go
  apis/storage/v1alpha1/zz_generated.conversion.go
  apis/storage/v1alpha1/zz_generated.deepcopy.go
  apis/storage/validation/volume.go
  apis/storage/validation/volume_test.go
  apis/storage/volume_types.go
  apis/storage/zz_generated.deepcopy.go
  generated/openapi/zz_generated.openapi.go
  machinebroker/api/v1alpha1/common_types.go
  machinebroker/apiutils/apiutils.go
  machinebroker/cleaner/cleaner.go
  machinebroker/server/common.go
  machinebroker/server/errors.go
  machinebroker/server/machine.go
  machinebroker/server/machine_create.go
  machinebroker/server/machine_create_test.go
  machinebroker/server/machine_delete.go
  machinebroker/server/machine_list.go
  machinebroker/server/machine_status.go
  machinebroker/server/networkinterface.go
  machinebroker/server/networkinterface_create.go
  machinebroker/server/networkinterface_delete.go
  machinebroker/server/networkinterface_list.go
  machinebroker/server/networkinterface_update.go
  machinebroker/server/server.go
  machinebroker/server/server_suite_test.go
  machinebroker/server/volume.go
  machinebroker/server/volume_create.go
  machinebroker/server/volume_delete.go
  machinebroker/server/volume_list.go
  machinepoollet/controllers/machine_controller.go
  machinepoollet/controllers/util.go
  onmetal-controller-manager/client/client.go
  onmetal-controller-manager/controllers/compute/machine_controller_test.go
  onmetal-controller-manager/controllers/compute/suite_test.go
  onmetal-controller-manager/controllers/networking/networkinterface_controller.go
  onmetal-controller-manager/controllers/networking/networkinterface_controller_test.go
  onmetal-controller-manager/controllers/networking/suite_test.go
  onmetal-controller-manager/controllers/storage/volume_controller_test.go
  onmetal-controller-manager/controllers/storage/volume_scheduler.go
  onmetal-controller-manager/controllers/storage/volume_scheduler_test.go
  onmetal-controller-manager/controllers/storage/volumeclass_controller.go
  onmetal-controller-manager/controllers/storage/volumeclass_controller_test.go
  onmetal-controller-manager/main.go
  ori/apis/runtime/v1alpha1/api.pb.go
  ori/apis/runtime/v1alpha1/api.proto
Labels: enhancement, compute, storage, api-change, size/XXL, networking

#555 Implement `LoadBalancer` controller
  config/controller/rbac/role.yaml
  onmetal-controller-manager/client/client.go
  onmetal-controller-manager/controllers/networking/aliasprefix_controller.go
  onmetal-controller-manager/controllers/networking/loadbalancer_controller.go
  onmetal-controller-manager/controllers/networking/loadbalancer_controller_test.go
  onmetal-controller-manager/controllers/networking/networkinterface_controller.go
  onmetal-controller-manager/controllers/networking/suite_test.go
  onmetal-controller-manager/controllers/networking/virtualip_controller.go
  onmetal-controller-manager/main.go
Labels: size/L

#556 Fix network protection reconciler field name
  onmetal-controller-manager/controllers/networking/network_protection_controller.go
Labels: bug, size/XS

#559 Fix LoadBalancerRouting Networkref population
  onmetal-controller-manager/controllers/networking/loadbalancer_controller.go
  onmetal-controller-manager/controllers/networking/loadbalancer_controller_test.go
Labels: bug, size/S

#561 Add missing index
  onmetal-controller-manager/main.go
Labels: bug, size/XS

#562 Fix typo in `Indexer`
  onmetal-controller-manager/controllers/networking/network_protection_controller.go
  onmetal-controller-manager/main.go
Labels: bug, size/XS
