Repository ironcore-dev/ironcore, pull requests merged in 2023-01, with the labels that each got.

#597 Machine state Terminated & power specification
  api/compute/v1alpha1/machine_types.go
  broker/machinebroker/server/machine.go
  client-go/applyconfigurations/compute/v1alpha1/machinespec.go
  client-go/applyconfigurations/internal/internal.go
  client-go/openapi/zz_generated.openapi.go
  onmetal-apiserver/internal/apis/compute/machine_types.go
  onmetal-apiserver/internal/apis/compute/v1alpha1/defaults.go
  onmetal-apiserver/internal/apis/compute/v1alpha1/zz_generated.conversion.go
  onmetal-apiserver/internal/apis/compute/v1alpha1/zz_generated.defaults.go
  onmetal-apiserver/internal/apis/compute/validation/machine.go
  onmetal-apiserver/internal/apis/compute/validation/machine_test.go
  ori/apis/machine/v1alpha1/api.pb.go
  ori/apis/machine/v1alpha1/api.proto
  poollet/machinepoollet/controllers/machine_controller.go
Labels: enhancement, size/L

#600 Broker / manage machine power state
  api/compute/v1alpha1/machine_types.go
  broker/machinebroker/server/machine_create.go
  broker/machinebroker/server/machine_powerstate_update.go
  client-go/applyconfigurations/compute/v1alpha1/machinespec.go
  client-go/openapi/zz_generated.openapi.go
  onmetal-apiserver/internal/apis/compute/machine_types.go
  onmetal-apiserver/internal/apis/compute/v1alpha1/defaults.go
  onmetal-apiserver/internal/apis/compute/v1alpha1/zz_generated.conversion.go
  onmetal-apiserver/internal/apis/compute/validation/machine.go
  onmetal-apiserver/internal/apis/compute/validation/machine_test.go
  ori/apis/machine/machine.go
  ori/apis/machine/v1alpha1/api.pb.go
  ori/apis/machine/v1alpha1/api.proto
  ori/remote/machine/runtime.go
  ori/testing/machine/fake.go
  poollet/machinepoollet/controllers/machine_controller.go
  poollet/machinepoollet/controllers/machine_controller_test.go
Labels: enhancement, size/XXL

#604 ori-machine: version rpc & usage in onmetal-api
  api/compute/v1alpha1/machine_types.go
  broker/machinebroker/server/version.go
  broker/machinebroker/version/version.go
  client-go/applyconfigurations/compute/v1alpha1/machinestatus.go
  client-go/applyconfigurations/internal/internal.go
  client-go/openapi/zz_generated.openapi.go
  onmetal-apiserver/internal/apis/compute/machine_types.go
  onmetal-apiserver/internal/apis/compute/v1alpha1/zz_generated.conversion.go
  ori/apis/machine/machine.go
  ori/apis/machine/v1alpha1/api.pb.go
  ori/apis/machine/v1alpha1/api.proto
  ori/remote/machine/runtime.go
  ori/testing/machine/fake.go
  poollet/machinepoollet/cmd/machinepoollet/app/app.go
  poollet/machinepoollet/controllers/controllers_suite_test.go
  poollet/machinepoollet/controllers/machine_controller.go
  poollet/machinepoollet/controllers/machine_controller_test.go
  poollet/machinepoollet/machine/machine.go
Labels: enhancement, size/XXL

#615 Bump dependencies
  client-go/openapi/zz_generated.openapi.go
  go.mod
  go.sum
Labels: enhancement, size/M

#603 Storage encryption proposal
  docs/proposals/06-storage-encryption.md
Labels: documentation, size/M

#618 Implemented storage encryption feature support
  api/compute/v1alpha1/machine_types.go
  api/storage/v1alpha1/volume_types.go
  api/storage/v1alpha1/zz_generated.deepcopy.go
  client-go/applyconfigurations/internal/internal.go
  client-go/applyconfigurations/storage/v1alpha1/volumeencryption.go
  client-go/applyconfigurations/storage/v1alpha1/volumespec.go
  client-go/applyconfigurations/utils.go
  client-go/openapi/zz_generated.openapi.go
  docs/api-reference/compute.md
  docs/api-reference/networking.md
  docs/api-reference/storage.md
  go.mod
  go.sum
  onmetal-apiserver/internal/apis/compute/machine_types.go
  onmetal-apiserver/internal/apis/storage/v1alpha1/zz_generated.conversion.go
  onmetal-apiserver/internal/apis/storage/validation/volume.go
  onmetal-apiserver/internal/apis/storage/validation/volume_test.go
  onmetal-apiserver/internal/apis/storage/volume_types.go
  onmetal-apiserver/internal/apis/storage/zz_generated.deepcopy.go
Labels: documentation, enhancement, size/XXL

#625 Fix machinepoollet network interface deletion
  poollet/machinepoollet/controllers/machine_controller_networkinterface.go
  poollet/machinepoollet/controllers/machine_controller_test.go
Labels: bug, size/L

#626 Fix volumepoollet startup
  poollet/volumepoollet/cmd/volumepoollet/app/app.go
Labels: bug, size/M
