Repository ironcore-dev/ironcore, pull requests merged in 2023-07, with the labels that each got.

#788 Add `breaking` category to release drafter configuration
  .github/release-drafter.yml
Labels: chore, size/XS

#789 Add documentation on machine exec flow
  docs/concepts/machine-exec-flow.md
  mkdocs.yml
Labels: documentation, size/L

#810 Change `listen-client-urls` in etcd `StatefulSet`
  config/apiserver/etcd/etcd.yaml
Labels: enhancement, size/XS
