Repository ironcore-dev/ironcore, pull requests merged in 2023-08, with the labels that each got.

#687 Add GH workflow to clean cache artefacts once a PR is closed
  .github/workflows/clean-cache.yml
Labels: chore, size/M

#822 Update golangci-lint version in GitHub actions workflow
  .github/workflows/lint.yml
Labels: chore, size/XS

#820 Improved `Volume` Scheduler to respect `Allocatable` resources
  cmd/onmetal-controller-manager/main.go
  internal/controllers/storage/scheduler/cache.go
  internal/controllers/storage/suite_test.go
  internal/controllers/storage/volume_scheduler.go
  internal/controllers/storage/volume_scheduler_test.go
Labels: enhancement, size/XXL

#832 Improved `orictl`
  orictl-machine/cmd/orictl-machine/orictlmachine/common/common.go
  orictl-machine/cmd/orictl-machine/orictlmachine/get/status/status.go
  orictl-machine/tableconverters/status.go
  orictl-volume/cmd/orictl-volume/orictlvolume/common/common.go
  orictl-volume/cmd/orictl-volume/orictlvolume/get/get.go
  orictl-volume/cmd/orictl-volume/orictlvolume/get/status/status.go
  orictl-volume/tableconverters/status.go
Labels: enhancement, size/M
