Repository ironcore-dev/ironcore, pull requests merged in 2023-09, with the labels that each got.

#844 Fix envtest renderAPIServices
  utils/envtest/apiservice.go
Labels: bug, size/S

#847 Envtest: allow additional aggregated APIs
  utils/envtest/apiservice.go
  utils/envtest/envtest.go
Labels: enhancement, size/L

#866 Fix `Indexer`
  poollet/machinepoollet/cmd/machinepoollet/app/app.go
  poollet/volumepoollet/cmd/volumepoollet/app/app.go
Labels: bug, size/S

#868 Fix resource accumulation
  broker/machinebroker/server/status.go
  broker/volumebroker/server/status.go
Labels: bug, size/XS

#872 Fix load balancer controller by nic enqueueing
  internal/controllers/networking/loadbalancer_controller.go
  internal/controllers/networking/loadbalancer_controller_test.go
Labels: bug, size/M

#873 Change size bytes from `uint64` to `int64`
  broker/machinebroker/server/machine.go
  broker/machinebroker/server/status.go
  broker/volumebroker/server/status.go
  broker/volumebroker/server/volume.go
  internal/controllers/compute/scheduler/cache.go
  ori/apis/machine/v1alpha1/api.pb.go
  ori/apis/machine/v1alpha1/api.proto
  ori/apis/volume/v1alpha1/api.pb.go
  ori/apis/volume/v1alpha1/api.proto
  poollet/machinepoollet/controllers/controllers_suite_test.go
  poollet/machinepoollet/controllers/machine_controller.go
  poollet/machinepoollet/controllers/machine_controller_volume.go
  poollet/machinepoollet/controllers/machinepool_controller_test.go
  poollet/machinepoollet/mcm/generic.go
  poollet/volumepoollet/controllers/volume_controller.go
  poollet/volumepoollet/controllers/volume_controller_test.go
  poollet/volumepoollet/controllers/volumepool_controller_test.go
Labels: bug, size/L

#875 Fix ephemeral resource handling
  api/common/v1alpha1/common_types.go
  go.mod
  go.sum
  internal/controllers/compute/machine_ephemeralnetworkinterface_controller.go
  internal/controllers/compute/machine_ephemeralnetworkinterface_controller_test.go
  internal/controllers/compute/machine_ephemeralvolume_controller.go
  internal/controllers/compute/machine_ephemeralvolume_controller_test.go
  internal/controllers/networking/loadbalancer_ephemeralprefix_controller.go
  internal/controllers/networking/loadbalancer_ephemeralprefix_controller_test.go
  internal/controllers/networking/networkinterface_ephemeralprefix_controller.go
  internal/controllers/networking/networkinterface_ephemeralprefix_controller_test.go
  internal/controllers/networking/networkinterface_ephemeralvirtualip_controller.go
  internal/controllers/networking/networkinterface_ephemeralvirtualip_controller_test.go
  utils/annotations/annotations.go
Labels: bug, size/L
