Repository ironcore-dev/ironcore, pull requests merged in 2023-11, with the labels that each got.

#910 Use `vgopath` setup consistently
  hack/update-codegen.sh
  hack/update-proto.sh
Labels: enhancement, size/XS

#911 Improve linting in project
  .github/workflows/lint.yml
  .golangci.yaml
  Makefile
  internal/admission/plugin/volumeresizepolicy/admission_test.go
  internal/app/compute_test.go
  internal/app/storage_test.go
  internal/controllers/compute/suite_test.go
  internal/controllers/core/core_suite_test.go
  internal/controllers/networking/network_protection_controller_test.go
  utils/context/context_test.go
Labels: enhancement, size/M

#923 Fix MachineID field in the Attach Volume call of orictl
  irictl-machine/cmd/irictl-machine/irictlmachine/attach/volume/volume.go
Labels: bug, size/XS

#927 Use `ironcore` `openapi-extractor`
  Makefile
  irictl-machine/config/samples/machine.yaml
  irictl-volume/config/samples/volume.yaml
  poollet/machinepoollet/iri/streaming/remotecommand/streams.go
Labels: chore, size/S
