Repository ironcore-dev/ironcore, pull requests merged in 2023-02, with the labels that each got.

#608 Resource Quota Proposal
  docs/proposals/07-quota.md
Labels: documentation, size/L

#638 Implement bucket quota tracking
  api/core/v1alpha1/resourcequota_types.go
  internal/apis/core/resourcequota_types.go
  internal/controllers/core/quota/storage/storage.go
  internal/quota/evaluator/onmetal/onmetal.go
  internal/quota/evaluator/storage/bucket.go
  internal/quota/evaluator/storage/storage.go
Labels: enhancement, size/L

#639 Implement additional field selectors
  api/compute/v1alpha1/common.go
  api/storage/v1alpha1/common.go
  docs/api-reference/core.md
  internal/apis/compute/common.go
  internal/apis/compute/v1alpha1/conversions.go
  internal/apis/storage/common.go
  internal/apis/storage/v1alpha1/conversions.go
  internal/app/app_suite_test.go
  internal/app/compute_test.go
  internal/app/core_test.go
  internal/app/storage_test.go
  internal/registry/compute/machine/strategy.go
  internal/registry/storage/bucket/strategy.go
  internal/registry/storage/volume/strategy.go
Labels: documentation, enhancement, size/XL

#641 Enhance `<kind>Class` controllers
  cmd/onmetal-controller-manager/main.go
  internal/client/compute.go
  internal/client/storage.go
  internal/controllers/compute/machineclass_controller.go
  internal/controllers/compute/suite_test.go
  internal/controllers/networking/suite_test.go
  internal/controllers/storage/bucketclass_controller.go
  internal/controllers/storage/suite_test.go
  internal/controllers/storage/volumeclass_controller.go
Labels: enhancement, size/L

#642 Increase default NAT Gateway port range from 64 to 2048
  api/networking/v1alpha1/natgateway_type.go
  client-go/openapi/zz_generated.openapi.go
  docs/api-reference/networking.md
  internal/apis/networking/natgateway_type.go
  internal/apis/networking/v1alpha1/defaults.go
  poollet/machinepoollet/controllers/machine_controller_test.go
Labels: documentation, enhancement, size/S

#651 Implement bootstrap token auth for all `*Pool`s
  Makefile
  api/compute/v1alpha1/common.go
  api/storage/v1alpha1/common.go
  cmd/onmetal-controller-manager/main.go
  config/apiserver/rbac/bucketpool_bootstrapper_role.yaml
  config/apiserver/rbac/bucketpool_bootstrapper_rolebinding.yaml
  config/apiserver/rbac/bucketpool_role.yaml
  config/apiserver/rbac/bucketpool_rolebinding.yaml
  config/apiserver/rbac/kustomization.yaml
  config/apiserver/rbac/machinepool_bootstrapper_role.yaml
  config/apiserver/rbac/machinepool_bootstrapper_rolebinding.yaml
  config/apiserver/rbac/machinepool_role.yaml
  config/apiserver/rbac/machinepool_rolebinding.yaml
  config/apiserver/rbac/volumepool_bootstrapper_role.yaml
  config/apiserver/rbac/volumepool_bootstrapper_rolebinding.yaml
  config/apiserver/rbac/volumepool_role.yaml
  config/apiserver/rbac/volumepool_rolebinding.yaml
  config/controller/rbac/role.yaml
  internal/apis/compute/common.go
  internal/apis/storage/common.go
  internal/controllers/core/certificate/compute/compute.go
  internal/controllers/core/certificate/compute/machinepool.go
  internal/controllers/core/certificate/generic/certificate.go
  internal/controllers/core/certificate/onmetal/onmetal.go
  internal/controllers/core/certificate/storage/bucketpool.go
  internal/controllers/core/certificate/storage/storage.go
  internal/controllers/core/certificate/storage/volumepool.go
  internal/controllers/core/certificateapproval_controller.go
  internal/controllers/core/certificateapproval_test.go
  internal/controllers/core/core_suite_test.go
  ori/apis/bucket/v1alpha1/api.pb.go
  ori/apis/machine/v1alpha1/api.pb.go
  ori/apis/volume/v1alpha1/api.pb.go
  poollet/bucketpoollet/client/config/getter.go
  poollet/bucketpoollet/cmd/bucketpoollet/app/app.go
  poollet/machinepoollet/client/config/getter.go
  poollet/machinepoollet/cmd/machinepoollet/app/app.go
  poollet/volumepoollet/client/config/getter.go
  poollet/volumepoollet/cmd/volumepoollet/app/app.go
  utils/certificate/certificate.go
  utils/certificate/certificate_suite_test.go
  utils/certificate/rotator.go
  utils/certificate/rotator_test.go
  utils/certificate/testing/fake.go
  utils/client/config/config.go
  utils/client/config/config_suite_test.go
  utils/client/config/controller.go
  utils/client/config/controller_test.go
  utils/client/config/errors.go
  utils/client/config/loader.go
  utils/client/config/loader_test.go
  utils/client/config/options.go
  utils/client/config/store.go
  utils/client/config/store_test.go
  utils/clientcmd/clientcmd.go
  utils/rest/configrotator.go
  utils/rest/configrotator_test.go
  utils/rest/rest_suite_test.go
  utils/rest/testing/fake.go
  utils/rest/util.go
Labels: enhancement, size/XXL
