Repository ironcore-dev/ironcore, pull requests merged in 2024-05, with the labels that each got.

#1061 Make `ChannelCapacity` configurable in `poollet`
  poollet/bucketpoollet/cmd/bucketpoollet/app/app.go
  poollet/machinepoollet/cmd/machinepoollet/app/app.go
  poollet/volumepoollet/cmd/volumepoollet/app/app.go
Labels: enhancement, size/S

#1064 Remove peering status handling in network peering reconciler
  cmd/ironcore-controller-manager/main.go
  internal/controllers/networking/network_peering_controller.go
  internal/controllers/networking/network_peering_controller_test.go
  internal/controllers/networking/network_protection_controller_test.go
Labels: enhancement, size/L

#1071 Fix gRPC client initialization
  go.mod
  go.sum
  iri/remote/machine/runtime.go
  iri/remote/volume/runtime.go
  irictl-bucket/cmd/irictl-bucket/irictlbucket/common/common.go
  irictl-machine/cmd/irictl-machine/irictlmachine/common/common.go
  irictl-volume/cmd/irictl-volume/irictlvolume/common/common.go
  poollet/bucketpoollet/cmd/bucketpoollet/app/app.go
  poollet/volumepoollet/cmd/volumepoollet/app/app.go
Labels: bug, size/M
