Repository ironcore-dev/ironcore, pull requests merged in 2024-04, with the labels that each got.

#1026 Implement `Network` peering controller and extend `NetworkPeeringStatus` with `State` field
  api/networking/v1alpha1/network_type.go
  client-go/applyconfigurations/internal/internal.go
  client-go/applyconfigurations/networking/v1alpha1/networkpeeringstatus.go
  client-go/openapi/zz_generated.openapi.go
  cmd/ironcore-controller-manager/main.go
  internal/apis/networking/network_type.go
  internal/apis/networking/v1alpha1/zz_generated.conversion.go
  internal/client/networking/network.go
  internal/controllers/networking/network_peering_controller.go
  internal/controllers/networking/network_peering_controller_test.go
  internal/controllers/networking/network_protection_controller.go
  internal/controllers/networking/network_protection_controller_test.go
  internal/controllers/networking/network_release_controller.go
  internal/controllers/networking/suite_test.go
Labels: enhancement, size/XXL

#1052 Fix irictl-machine `AttachNetworkInterfaceRequest`
  irictl-machine/cmd/irictl-machine/irictlmachine/attach/networkinterface/networkinterface.go
Labels: bug, size/XS

#1053 Bump golang to 1.22.2 and other housekeeping tasks
  .github/dependabot.yml
  .github/workflows/lint.yml
  .github/workflows/release-drafter.yml
  .github/workflows/size-label.yml
  Makefile
  go.mod
  internal/admission/plugin/volumeresizepolicy/admission_test.go
Labels: chore, size/M

#1055 Change network peering states as Ready, Error & Pending
  api/networking/v1alpha1/network_type.go
  docs/api-reference/compute.md
  docs/api-reference/networking.md
  internal/apis/networking/network_type.go
  internal/controllers/networking/network_peering_controller_test.go
Labels: documentation, enhancement, size/L

#1056 Fix duplicate make target
  Makefile
  gen/swagger.json
  gen/v3/apis__compute.ironcore.dev__v1alpha1_openapi.json
  gen/v3/apis__networking.ironcore.dev__v1alpha1_openapi.json
Labels: bug, size/S
