Repository ironcore-dev/ironcore, pull requests merged in 2024-11, with the labels that each got.

#1144 Add e2e example manifests for `Network` peering
  config/samples/e2e/bases/network-peering/kustomization.yaml
  config/samples/e2e/bases/network-peering/machine1.yaml
  config/samples/e2e/bases/network-peering/machine2.yaml
  config/samples/e2e/bases/network-peering/network1.yaml
  config/samples/e2e/bases/network-peering/network2.yaml
  config/samples/e2e/network-peering/README.md
  config/samples/e2e/network-peering/kustomization.yaml
Labels: documentation, enhancement, size/L

#1136 Add e2e example for `Machine` creation using ephemeral resources
  config/samples/e2e/bases/machine-with-ephemeral-resources/kustomization.yaml
  config/samples/e2e/bases/machine-with-ephemeral-resources/machine.yaml
  config/samples/e2e/bases/machine-with-ephemeral-resources/network.yaml
  config/samples/e2e/bases/machine-with-nonephemeral-resources/kustomization.yaml
  config/samples/e2e/bases/machine-with-nonephemeral-resources/machine.yaml
  config/samples/e2e/bases/machine-with-nonephemeral-resources/network.yaml
  config/samples/e2e/bases/machine-with-nonephemeral-resources/networkinterface.yaml
  config/samples/e2e/bases/machine-with-nonephemeral-resources/virtualIP.yaml
  config/samples/e2e/bases/machine-with-nonephemeral-resources/volume.yaml
  config/samples/e2e/machine-with-ephemeral-resources/README.md
  config/samples/e2e/machine-with-ephemeral-resources/kustomization.yaml
  config/samples/e2e/machine-with-non-ephemeral-resources/README.md
  config/samples/e2e/machine-with-non-ephemeral-resources/kustomization.yaml
Labels: documentation, enhancement, size/L

#1145 Add e2e `IPAM` example manifests for `IPv4` and `IPv6`
  config/samples/e2e/bases/ipam-ipv4/child-prefix.yaml
  config/samples/e2e/bases/ipam-ipv4/kustomization.yaml
  config/samples/e2e/bases/ipam-ipv4/parent-prefix.yaml
  config/samples/e2e/bases/ipam-ipv6/child-prefix.yaml
  config/samples/e2e/bases/ipam-ipv6/kustomization.yaml
  config/samples/e2e/bases/ipam-ipv6/parent-prefix.yaml
  config/samples/e2e/ipam-ipv4/README.md
  config/samples/e2e/ipam-ipv4/kustomization.yaml
  config/samples/e2e/ipam-ipv6/README.md
  config/samples/e2e/ipam-ipv6/kustomization.yaml
Labels: documentation, enhancement, size/M

#1167 Bump `k8s.io/*` deps to v0.30.7
  .github/dependabot.yml
  client-go/openapi/zz_generated.openapi.go
  go.mod
  go.sum
Labels: enhancement, size/M

#1169 Fix IRI `*-broker` status
  broker/bucketbroker/server/bucketclass_list.go
  broker/machinebroker/server/status.go
  broker/volumebroker/server/status.go
Labels: bug, size/XS

#1166 Add `ChannelCapacity`, `RelistPeriod` and `RelistThreshold` flags to *-poollets event re-listing
  poollet/bucketpoollet/cmd/bucketpoollet/app/app.go
  poollet/machinepoollet/cmd/machinepoollet/app/app.go
  poollet/volumepoollet/cmd/volumepoollet/app/app.go
Labels: bug, size/M

#1163 Fix flapping IPs in NetworkInterface status
  poollet/machinepoollet/controllers/controllers_suite_test.go
  poollet/machinepoollet/controllers/machine_controller.go
  poollet/machinepoollet/controllers/machine_controller_test.go
Labels: bug, size/S

#1170 Fix `Dockerfile` linting issues
  Dockerfile
Labels: chore, size/M
