Repository ironcore-dev/ironcore, pull requests merged in 2024-12, with the labels that each got.

#1176 Harmonize rest config setup for brokers
  broker/bucketbroker/client/config/getter.go
  broker/bucketbroker/cmd/bucketbroker/app/app.go
  broker/machinebroker/client/config/getter.go
  broker/machinebroker/cmd/machinebroker/app/app.go
  broker/volumebroker/client/config/getter.go
  broker/volumebroker/cmd/volumebroker/app/app.go
  utils/client/config/config.go
Labels: enhancement, size/L

#1177 Fix flag declaration in `*-broker`s
  broker/bucketbroker/cmd/bucketbroker/app/app.go
  broker/machinebroker/cmd/machinebroker/app/app.go
  broker/volumebroker/cmd/volumebroker/app/app.go
  utils/client/config/config.go
  utils/client/config/options.go
Labels: bug, size/S

#1179 Fix sporadic timeout error for core_test
  internal/app/core_test.go
Labels: bug, size/XS

#1188 Add `NetworkPolicy` e2e test manifests with docs
  config/samples/e2e/bases/network-policy/kustomization.yaml
  config/samples/e2e/bases/network-policy/machine1.yaml
  config/samples/e2e/bases/network-policy/machine2.yaml
  config/samples/e2e/bases/network-policy/network-policy.yaml
  config/samples/e2e/bases/network-policy/network.yaml
  config/samples/e2e/network-policy/README.md
  config/samples/e2e/network-policy/kustomization.yaml
Labels: documentation, size/L

#1189 Add basic usage documentation structure
  docs/README.md
  docs/api-reference/overview.md
  docs/architecture/iri.md
  docs/architecture/overview.md
  docs/development/contribution.md
  docs/development/documentation.md
  docs/development/setup.md
  docs/development/testing.md
  docs/proposals/00-template.md
  docs/proposals/01-networking-integration.md
  docs/proposals/02-machine-console-access.md
  docs/proposals/03-loadbalancer.md
  docs/proposals/04-nat-gateway.md
  docs/proposals/05-object-storage.md
  docs/proposals/06-storage-encryption.md
  docs/proposals/07-quota.md
  docs/proposals/08-internal-load-balancer.md
  docs/proposals/09-network-peering.md
  docs/proposals/10-network-policies.md
  docs/usage/compute/machine.md
  docs/usage/compute/machineclass.md
  docs/usage/compute/machinepool.md
  docs/usage/core/resourcequota.md
  docs/usage/installation.md
  docs/usage/ipam/prefix.md
  docs/usage/networking/loadbalancer.md
  docs/usage/networking/natgateway.md
  docs/usage/networking/network.md
  docs/usage/networking/networkinterface.md
  docs/usage/networking/networkpolicy.md
  docs/usage/networking/virtualip.md
  docs/usage/storage/bucket.md
  docs/usage/storage/bucketclass.md
  docs/usage/storage/bucketpool.md
  docs/usage/storage/volume.md
  docs/usage/storage/volumeclass.md
  docs/usage/storage/volumepool.md
  hack/docs/abbreviations.md
  mkdocs.yml
Labels: documentation, enhancement, size/L

#1201 Remove IPs and VirtualIPs from `Machine` NIC status
  .github/workflows/lint.yml
  Makefile
  api/compute/v1alpha1/machine_types.go
  api/compute/v1alpha1/zz_generated.deepcopy.go
  client-go/applyconfigurations/compute/v1alpha1/networkinterfacestatus.go
  client-go/applyconfigurations/internal/internal.go
  client-go/openapi/api_violations.report
  client-go/openapi/zz_generated.openapi.go
  docs/api-reference/compute.md
  gen/swagger.json
  gen/v3/apis__compute.ironcore.dev__v1alpha1_openapi.json
  gen/v3/apis__core.ironcore.dev__v1alpha1_openapi.json
  gen/v3/apis__ipam.ironcore.dev__v1alpha1_openapi.json
  gen/v3/apis__networking.ironcore.dev__v1alpha1_openapi.json
  gen/v3/apis__storage.ironcore.dev__v1alpha1_openapi.json
  internal/apis/compute/machine_types.go
  internal/apis/compute/v1alpha1/zz_generated.conversion.go
  internal/apis/compute/zz_generated.deepcopy.go
Labels: documentation, enhancement, size/XXL, breaking

#1202 Do not update `NetworkInterface` IPs in status via poollet
  iri/apis/machine/v1alpha1/api.pb.go
  iri/apis/machine/v1alpha1/api.proto
  poollet/machinepoollet/controllers/machine_controller.go
  poollet/machinepoollet/controllers/machine_controller_test.go
Labels: bug, size/L, breaking

#1205 Add missing RBAC permissions to the `apiserver_role.yaml`
  config/apiserver/rbac/apiserver_role.yaml
Labels: size/XS
