Repository ironcore-dev/ironcore, pull requests merged in 2024-10, with the labels that each got.

#1126 Added `NetworkInterfaceRef` to `Machine` status
  api/compute/v1alpha1/machine_types.go
  api/compute/v1alpha1/zz_generated.deepcopy.go
  client-go/applyconfigurations/compute/v1alpha1/networkinterfacestatus.go
  client-go/applyconfigurations/internal/internal.go
  client-go/openapi/zz_generated.openapi.go
  gen/swagger.json
  gen/v3/apis__compute.ironcore.dev__v1alpha1_openapi.json
  gen/v3/apis__networking.ironcore.dev__v1alpha1_openapi.json
  internal/apis/compute/machine_types.go
  internal/apis/compute/v1alpha1/zz_generated.conversion.go
  internal/apis/compute/zz_generated.deepcopy.go
  poollet/machinepoollet/controllers/machine_controller_networkinterface.go
  poollet/machinepoollet/controllers/machine_controller_test.go
Labels: enhancement, size/L

#1125 Added `VolumeRef` to `Machine` status
  api/compute/v1alpha1/machine_types.go
  api/compute/v1alpha1/zz_generated.deepcopy.go
  client-go/applyconfigurations/compute/v1alpha1/volumestatus.go
  client-go/applyconfigurations/internal/internal.go
  client-go/openapi/zz_generated.openapi.go
  gen/swagger.json
  gen/v3/apis__compute.ironcore.dev__v1alpha1_openapi.json
  internal/apis/compute/machine_types.go
  internal/apis/compute/v1alpha1/zz_generated.conversion.go
  internal/apis/compute/zz_generated.deepcopy.go
  internal/app/app_suite_test.go
  internal/app/core_test.go
  poollet/machinepoollet/controllers/machine_controller_test.go
  poollet/machinepoollet/controllers/machine_controller_volume.go
Labels: enhancement, size/L

#1133 Add e2e example for `Machine` creation using non ephemeral resources
  config/samples/e2e/bases/ignition/ignition-secret.yaml
  config/samples/e2e/bases/ignition/ignition.yaml
  config/samples/e2e/bases/ignition/index.html
  config/samples/e2e/bases/ignition/install-nginx.sh
  config/samples/e2e/bases/ignition/kustomization.yaml
  config/samples/e2e/bases/ignition/regenerate-ignition.sh
  config/samples/e2e/bases/nonephemeral-machine/kustomization.yaml
  config/samples/e2e/bases/nonephemeral-machine/machine.yaml
  config/samples/e2e/bases/nonephemeral-machine/network.yaml
  config/samples/e2e/bases/nonephemeral-machine/networkinterface.yaml
  config/samples/e2e/bases/nonephemeral-machine/virtualIP.yaml
  config/samples/e2e/bases/nonephemeral-machine/volume.yaml
  config/samples/e2e/machine-with-non-ephemeral-resource/README.md
  config/samples/e2e/machine-with-non-ephemeral-resource/kustomization.yaml
  internal/app/app_suite_test.go
Labels: documentation, enhancement, size/L

#1137 Add e2e example manifests for `LoadBalancer`
  config/samples/e2e/bases/loadbalancer-public/kustomization.yaml
  config/samples/e2e/bases/loadbalancer-public/loadbalancer.yaml
  config/samples/e2e/bases/loadbalancer-public/machine1.yaml
  config/samples/e2e/bases/loadbalancer-public/machine2.yaml
  config/samples/e2e/bases/loadbalancer-public/network.yaml
  config/samples/e2e/loadbalancer-public/README.md
  config/samples/e2e/loadbalancer-public/kustomization.yaml
Labels: documentation, enhancement, size/L

#1146 Do not use process substitution in `hack/update-codegen.sh`
  hack/update-codegen.sh
Labels: enhancement, size/XS
