Repository ironcore-dev/ironcore, pull requests merged in 2024-01, with the labels that each got.

#958 Bump `k8s.io/*` deps to `v1.29`
  Makefile
  client-go/applyconfigurations/internal/internal.go
  client-go/informers/factory.go
  client-go/openapi/zz_generated.openapi.go
  go.mod
  go.sum
  internal/apis/networking/v1alpha1/defaults.go
  internal/apis/networking/validation/loadbalancer_test.go
  internal/apis/networking/validation/natgateway_test.go
  internal/app/apiserver/apiserver.go
  internal/app/compute_test.go
  irictl-machine/cmd/irictl-machine/irictlmachine/exec/exec.go
  utils/certificate/rotator_test.go
  utils/envtest/apiserver/apiserver.go
  utils/envtest/envtest.go
  utils/maps/maps.go
  utils/rest/configrotator_test.go
  utils/sets/sets.go
Labels: enhancement, size/XL

#959 Regenerate v2/v3 OpenAPI definitions
  Makefile
  gen/swagger.json
  gen/v3/apis__compute.ironcore.dev__v1alpha1_openapi.json
  gen/v3/apis__core.ironcore.dev__v1alpha1_openapi.json
  gen/v3/apis__ipam.ironcore.dev__v1alpha1_openapi.json
  gen/v3/apis__networking.ironcore.dev__v1alpha1_openapi.json
  gen/v3/apis__storage.ironcore.dev__v1alpha1_openapi.json
Labels: chore, size/XL

#960 Add print column for `Prefixes` in `NetworkInterface`
  internal/registry/networking/networkinterface/storage/tableconvertor.go
Labels: bug, enhancement, size/S

#963 Switch to `enable-priority-and-fairness` flag in `apiserver` deployment
  config/apiserver/default/apiserver_certificate_patch.yaml
  config/apiserver/etcdless/apiserver_certificate_patch.yaml
  config/apiserver/server/server.yaml
Labels: enhancement, size/XS

#961 Populate `NetworkInterface` status via `machinepoollet`
  iri/apis/machine/v1alpha1/api.pb.go
  iri/apis/machine/v1alpha1/api.proto
  poollet/machinepoollet/controllers/machine_controller.go
  poollet/machinepoollet/controllers/machine_controller_networkinterface.go
  poollet/machinepoollet/controllers/machine_controller_test.go
Labels: enhancement, size/L

#965 Fix RBAC: Allow `machinepoollet` to update NIC status
  config/apiserver/rbac/machinepool_role.yaml
  config/machinepoollet-broker/poollet-rbac/role.yaml
  poollet/machinepoollet/controllers/machine_controller.go
Labels: bug, size/S

#967 Fix IRI `NetworkInterface` preperation
  poollet/machinepoollet/controllers/machine_controller_networkinterface.go
Labels: bug, size/XS
