Repository ironcore-dev/ironcore, pull requests merged in 2024-07, with the labels that each got.

#1078 Add network peering prefixes types and its validation
  api/networking/v1alpha1/network_type.go
  api/networking/v1alpha1/zz_generated.deepcopy.go
  client-go/applyconfigurations/internal/internal.go
  client-go/applyconfigurations/networking/v1alpha1/networkpeering.go
  client-go/applyconfigurations/networking/v1alpha1/networkpeeringstatus.go
  client-go/applyconfigurations/networking/v1alpha1/peeringprefix.go
  client-go/applyconfigurations/networking/v1alpha1/peeringprefixes.go
  client-go/applyconfigurations/networking/v1alpha1/peeringprefixref.go
  client-go/applyconfigurations/networking/v1alpha1/peeringprefixstatus.go
  client-go/applyconfigurations/utils.go
  client-go/openapi/api_violations.report
  client-go/openapi/zz_generated.openapi.go
  docs/api-reference/networking.md
  internal/apis/networking/network_type.go
  internal/apis/networking/v1alpha1/zz_generated.conversion.go
  internal/apis/networking/validation/network.go
  internal/apis/networking/validation/network_test.go
  internal/apis/networking/zz_generated.deepcopy.go
Labels: bug, documentation, enhancement, size/XL

#1083 Fix peering prefix validation for `prefixRef` name
  internal/apis/networking/validation/network.go
Labels: bug, size/XS

#1084 Extend `bucketpoollet` and `volumepoollet` with IRI `RuntimeService` interface
  iri/apis/bucket/bucket.go
  iri/remote/bucket/runtime.go
  iri/testing/volume/fake.go
  poollet/bucketpoollet/bcm/generic.go
  poollet/bucketpoollet/cmd/bucketpoollet/app/app.go
  poollet/bucketpoollet/controllers/bucket_controller.go
  poollet/bucketpoollet/controllers/bucketpool_controller.go
  poollet/volumepoollet/cmd/volumepoollet/app/app.go
  poollet/volumepoollet/controllers/volume_controller.go
  poollet/volumepoollet/controllers/volumepool_controller.go
  poollet/volumepoollet/vcm/generic.go
Labels: enhancement, size/L

#1081 Extend Machine Runtime Interface to Support Cross-Cluster Events
  broker/machinebroker/apiutils/apiutils.go
  broker/machinebroker/server/event_list.go
  broker/machinebroker/server/event_list_test.go
  broker/machinebroker/server/machine_list.go
  broker/machinebroker/server/machine_networkinterface_attach.go
  broker/machinebroker/server/machine_volume_attach.go
  iri/apis/machine/machine.go
  iri/apis/machine/v1alpha1/api.pb.go
  iri/apis/machine/v1alpha1/api.proto
  iri/remote/machine/runtime.go
  iri/testing/machine/fake.go
  poollet/machinepoollet/cmd/machinepoollet/app/app.go
  poollet/machinepoollet/mem/mem.go
  poollet/machinepoollet/mem/mem_suite_test.go
  poollet/machinepoollet/mem/mem_test.go
Labels: enhancement, size/XXL

#1088 Fix `machinebroker` RBAC
  broker/machinebroker/server/server.go
  config/machinepoollet-broker/broker-rbac/role.yaml
Labels: bug, size/XS

#1089 Add `get events` command to `irictl-machine`
  .reuse/dep5
  broker/machinebroker/apiutils/apiutils.go
  broker/machinebroker/server/event_list.go
  broker/machinebroker/server/event_list_test.go
  hack/update-proto.sh
  iri/apis/event/v1alpha1/api.pb.go
  iri/apis/event/v1alpha1/api.proto
  iri/apis/machine/v1alpha1/api.pb.go
  iri/apis/machine/v1alpha1/api.proto
  iri/testing/machine/fake.go
  irictl-machine/cmd/irictl-machine/irictlmachine/get/event/event.go
  irictl-machine/cmd/irictl-machine/irictlmachine/get/get.go
  irictl-machine/tableconverters/event.go
  poollet/machinepoollet/mem/mem.go
  poollet/machinepoollet/mem/mem_test.go
Labels: bug, enhancement, size/XXL

#1090 Fix event object reference
  poollet/machinepoollet/mem/mem.go
Labels: bug, size/XS

#1093 Improved `irictl machine` get events command
  broker/machinebroker/server/event_list_test.go
  irictl-machine/cmd/irictl-machine/irictlmachine/get/event/event.go
Labels: bug, size/S

#1091 Extend Bucket Runtime Interface for Cross-Cluster Events
  broker/bucketbroker/server/bucket_create.go
  broker/bucketbroker/server/bucket_create_test.go
  broker/bucketbroker/server/bucket_delete_test.go
  broker/bucketbroker/server/bucket_list.go
  broker/bucketbroker/server/bucket_list_test.go
  broker/bucketbroker/server/bucketclass_list_test.go
  broker/bucketbroker/server/event_list.go
  broker/bucketbroker/server/event_list_test.go
  broker/bucketbroker/server/server.go
  broker/bucketbroker/server/server_suite_test.go
  config/bucketpoollet-broker/broker-rbac/role.yaml
  iri/apis/bucket/bucket.go
  iri/apis/bucket/v1alpha1/api.pb.go
  iri/apis/bucket/v1alpha1/api.proto
  iri/apis/machine/v1alpha1/api.proto
  iri/remote/bucket/runtime.go
  iri/testing/bucket/fake.go
  irictl-bucket/cmd/irictl-bucket/irictlbucket/get/event/event.go
  irictl-bucket/cmd/irictl-bucket/irictlbucket/get/get.go
  irictl-bucket/tableconverters/event.go
  poollet/bucketpoollet/bem/bem.go
  poollet/bucketpoollet/bem/bem_suite_test.go
  poollet/bucketpoollet/bem/bem_test.go
  poollet/bucketpoollet/cmd/bucketpoollet/app/app.go
  poollet/bucketpoollet/controllers/bucket_controller_test.go
  poollet/bucketpoollet/controllers/bucketpool_controller.go
  poollet/bucketpoollet/controllers/bucketpool_controller_test.go
  poollet/bucketpoollet/controllers/controllers_suite_test.go
  poollet/machinepoollet/controllers/machinepool_controller.go
  poollet/volumepoollet/controllers/volumepool_controller.go
Labels: enhancement, size/XXL
