Repository ironcore-dev/ironcore, pull requests merged in 2025-02, with the labels that each got.

#1228 Remove automerge workflow
  .github/workflows/dependabot-auto-merge.yml
Labels: chore, size/S

#1216 Add usage doc for `virtualIP`, `networkPolicy`, `networkInterface`, and `NATGateway`
  docs/usage/networking/natgateway.md
  docs/usage/networking/networkinterface.md
  docs/usage/networking/networkpolicy.md
  docs/usage/networking/virtualip.md
Labels: documentation, enhancement, size/L

#1221 Add usage docs for IPAM resources
  docs/proposals/01-networking-integration.md
  docs/proposals/02-machine-console-access.md
  docs/proposals/03-loadbalancer.md
  docs/proposals/04-nat-gateway.md
  docs/proposals/05-object-storage.md
  docs/proposals/07-quota.md
  docs/usage/ipam/prefix.md
Labels: documentation, enhancement, size/L

#1217 Add validation for `Machine` network interface spec
  internal/apis/compute/validation/machine.go
  internal/apis/compute/validation/machine_test.go
  internal/apis/networking/validation/networkinterface.go
Labels: bug, enhancement, size/L

#1230 Fix IRI `Volume` list update
  poollet/machinepoollet/controllers/machine_controller_test.go
  poollet/machinepoollet/controllers/machine_controller_volume.go
Labels: bug, size/L

#1243 Set correct `StreamIdleTimeout` value
  poollet/machinepoollet/iri/streaming/remotecommand/exec.go
Labels: bug, size/XS
