Repository ironcore-dev/ironcore, pull requests merged in 2025-01, with the labels that each got.

#1213 Add documentation for `storage` API resources
  docs/usage/installation.md
  docs/usage/storage/bucket.md
  docs/usage/storage/bucketclass.md
  docs/usage/storage/bucketpool.md
  docs/usage/storage/volume.md
  docs/usage/storage/volumeclass.md
  docs/usage/storage/volumepool.md
  gen/swagger.json
Labels: documentation, enhancement, size/XL

#1220 Revert `sigs.k8s.io/structured-merge-diff/v4` to `v4.4.1`
  go.mod
  go.sum
Labels: bug, size/S

#1212 Add usage doc for compute section
  docs/usage/compute/machine.md
  docs/usage/compute/machineclass.md
  docs/usage/compute/machinepool.md
Labels: documentation, enhancement, size/L

#1223 Fix sporadic test failure when attaching `NetworkInterfaces` to `Machines`
  broker/machinebroker/server/machine_networkinterface_attach_test.go
Labels: bug, enhancement, size/XS
