Repository ironcore-dev/ironcore, pull requests merged in 2025-03, with the labels that each got.

#1244 Update reuse configuration
  REUSE.toml
Labels: chore, size/M

#1241 Add usage documentation for `ResourceQuota`
  docs/usage/core/resourcequota.md
Labels: documentation, enhancement, size/M

#1260 Use `NameIsDNSSubdomain` validation for `NetworkInterface` and `Volume`
  internal/apis/compute/validation/machine.go
  internal/apis/networking/validation/networkinterface.go
  internal/apis/storage/validation/volume.go
Labels: enhancement, size/S

#1262 Fix error handling in `ResourceQuota` scope evaluator
  internal/quota/evaluator/compute/machine.go
  internal/quota/evaluator/storage/bucket.go
  internal/quota/evaluator/storage/volume.go
Labels: bug, size/S

#1263 Bump golang to 1.24
  go.mod
Labels: chore, size/XS
