Repository ironcore-dev/ironcore, pull requests merged in 2025-04, with the labels that each got.

#1268 Emit `Event` when `Volume` creation is exceeding `ResourceQuota`
  cmd/ironcore-controller-manager/main.go
  internal/controllers/compute/machine_ephemeralvolume_controller.go
Labels: enhancement, size/S

#1222 Introduce `ReclaimPolicy` for ephemeral `VirtualIP`
  api/networking/v1alpha1/virtualip_types.go
  api/networking/v1alpha1/zz_generated.deepcopy.go
  client-go/applyconfigurations/internal/internal.go
  client-go/applyconfigurations/networking/v1alpha1/ephemeralvirtualipspec.go
  client-go/applyconfigurations/networking/v1alpha1/virtualiptemplatespec.go
  client-go/applyconfigurations/utils.go
  client-go/openapi/zz_generated.openapi.go
  docs/api-reference/networking.md
  gen/swagger.json
  gen/v3/apis__compute.ironcore.dev__v1alpha1_openapi.json
  gen/v3/apis__networking.ironcore.dev__v1alpha1_openapi.json
  internal/apis/networking/v1alpha1/zz_generated.conversion.go
  internal/apis/networking/validation/virtualiptemplate.go
  internal/apis/networking/virtualip_types.go
  internal/apis/networking/zz_generated.deepcopy.go
  internal/controllers/networking/networkinterface_ephemeralvirtualip_controller.go
  internal/controllers/networking/networkinterface_ephemeralvirtualip_controller_test.go
  internal/controllers/networking/virtualip_release_controller_test.go
  internal/registry/networking/virtualip/strategy.go
  utils/annotations/annotations.go
Labels: documentation, enhancement, size/XL

#1139 Migrate proto generation to `buf`
  .golangci.yml
  Makefile
  REUSE.toml
  broker/bucketbroker/server/bucketclass_list.go
  broker/bucketbroker/server/server.go
  broker/machinebroker/cmd/machinebroker/app/app.go
  broker/machinebroker/server/machine_create.go
  broker/machinebroker/server/machine_volume_attach.go
  broker/machinebroker/server/server.go
  broker/machinebroker/server/status.go
  broker/volumebroker/server/server.go
  broker/volumebroker/server/status.go
  broker/volumebroker/server/volume_create.go
  broker/volumebroker/server/volume_expand.go
  buf.gen.yaml
  buf.yaml
  go.mod
  go.sum
  hack/tools.go
  hack/update-codegen.sh
  hack/update-proto.sh
  internal/apis/compute/validation/machine.go
  internal/controllers/ipam/prefixallocationscheduler_controller.go
  iri/apis/bucket/v1alpha1/api.pb.go
  iri/apis/bucket/v1alpha1/api.proto
  iri/apis/bucket/v1alpha1/api_grpc.pb.go
  iri/apis/event/v1alpha1/api.pb.go
  iri/apis/event/v1alpha1/api.proto
  iri/apis/machine/v1alpha1/api.pb.go
  iri/apis/machine/v1alpha1/api.proto
  iri/apis/machine/v1alpha1/api_grpc.pb.go
  iri/apis/meta/v1alpha1/api.pb.go
  iri/apis/meta/v1alpha1/api.proto
  iri/apis/meta/v1alpha1/interfaces.go
  iri/apis/volume/v1alpha1/api.pb.go
  iri/apis/volume/v1alpha1/api.proto
  iri/apis/volume/v1alpha1/api_grpc.pb.go
  iri/testing/bucket/fake.go
  iri/testing/machine/fake.go
  iri/testing/volume/fake.go
  irictl-machine/tableconverters/status.go
  poollet/bucketpoollet/bcm/generic.go
  poollet/bucketpoollet/controllers/bucket_controller.go
  poollet/bucketpoollet/controllers/bucketpool_controller.go
  poollet/bucketpoollet/controllers/controllers_suite_test.go
  poollet/irievent/generator.go
  poollet/machinepoollet/controllers/controllers_suite_test.go
  poollet/machinepoollet/controllers/machine_controller.go
  poollet/machinepoollet/controllers/machine_controller_networkinterface.go
  poollet/machinepoollet/controllers/machine_controller_test.go
  poollet/machinepoollet/controllers/machine_controller_volume.go
  poollet/machinepoollet/controllers/machinepool_controller.go
  poollet/machinepoollet/controllers/machinepool_controller_test.go
  poollet/machinepoollet/mcm/generic.go
  poollet/volumepoollet/controllers/controllers_suite_test.go
  poollet/volumepoollet/controllers/volume_controller.go
  poollet/volumepoollet/controllers/volumepool_controller.go
  poollet/volumepoollet/vcm/generic.go
  poollet/volumepoollet/vem/vem_test.go
  utils/envtest/internal/testing/addr/addr.go
Labels: enhancement, size/XXL

#1276 Update container build workflow
  .github/workflows/publish-docker.yml
Labels: chore, size/XS, ok-to-image

#1269 Add validation for `ResourceQuota` spec resource names.
  internal/api/validation/helper.go
  internal/apis/core/validation/resourcequota.go
  internal/apis/core/validation/resourcequota_test.go
Labels: bug, size/M

#1128 Reservation-Based Scheduling Proposal for `Machine`s
  docs/proposals/08-internal-load-balancer.md
  docs/proposals/11-scheduling.md
Labels: documentation, enhancement, size/L
