Repository ironcore-dev/ironcore, pull requests merged in 2025-08, with the labels that each got.

#1342 Update volume status received from IRI response
  internal/apis/compute/validation/machine.go
  internal/apis/compute/validation/machine_test.go
  poollet/machinepoollet/controllers/machine_controller_volume.go
Labels: bug, size/M, area/iaas

#1364 Fix flapping `NIC`s
  broker/machinebroker/server/machine.go
Labels: bug

#1349 Add `downwardAPILabel` support for `Network` resource
  broker/bucketbroker/server/bucket_create.go
  broker/common/utils/utils.go
  broker/machinebroker/networks/networks.go
  broker/machinebroker/server/machine.go
  broker/machinebroker/server/machine_create.go
  broker/machinebroker/server/machine_list.go
  broker/machinebroker/server/machine_networkinterface_attach.go
  broker/machinebroker/server/machine_networkinterface_attach_test.go
  broker/machinebroker/server/networkinterface.go
  broker/machinebroker/server/server_suite_test.go
  broker/volumebroker/server/volume_create.go
  config/machinepoollet-broker/manager/manager.yaml
  iri/apis/machine/v1alpha1/api.pb.go
  iri/apis/machine/v1alpha1/api.proto
  poollet/bucketpoollet/controllers/bucket_controller.go
  poollet/common/utils/utils.go
  poollet/machinepoollet/api/v1alpha1/common_types.go
  poollet/machinepoollet/cmd/machinepoollet/app/app.go
  poollet/machinepoollet/controllers/controllers_suite_test.go
  poollet/machinepoollet/controllers/machine_controller.go
  poollet/machinepoollet/controllers/machine_controller_networkinterface.go
  poollet/machinepoollet/controllers/machine_controller_test.go
  poollet/volumepoollet/controllers/volume_controller.go
Labels: enhancement, size/XL, area/iaas

#1363 Remove `downward-api` label filtering dependency
  broker/machinebroker/server/machine_create.go
  broker/machinebroker/server/machine_create_test.go
  broker/machinebroker/server/machine_list.go
  poollet/machinepoollet/api/v1alpha1/common_types.go
  poollet/machinepoollet/controllers/controllers_suite_test.go
  poollet/machinepoollet/controllers/machine_controller.go
  poollet/machinepoollet/controllers/machine_controller_test.go
  poollet/machinepoollet/mem/mem_test.go
Labels: bug, size/L, area/iaas

#1370 Bump dependencies
  go.mod
  go.sum
Labels: chore, size/L
