Repository ironcore-dev/ironcore, pull requests merged in 2025-07, with the labels that each got.

#1322 Fix peering validation to allow IP range
  internal/apis/networking/validation/network.go
  internal/apis/networking/validation/network_test.go
Labels: bug, size/M, area/iaas

#1311 Change `MachineClass` capabilities to support arbitrary resources
  broker/machinebroker/server/status.go
  internal/controllers/compute/machine_scheduler_test.go
  iri/apis/machine/v1alpha1/api.pb.go
  iri/apis/machine/v1alpha1/api.proto
  irictl-machine/tableconverters/status.go
  poollet/machinepoollet/controllers/controllers_suite_test.go
  poollet/machinepoollet/controllers/machine_controller.go
  poollet/machinepoollet/controllers/machinepool_controller_test.go
  poollet/machinepoollet/mcm/generic.go
  poollet/machinepoollet/mem/mem_test.go
Labels: enhancement, size/L, breaking, area/iaas

#1320 Respect label filter in `ListMachines`
  broker/machinebroker/server/machine_list.go
Labels: bug, size/M, area/iaas

#1317 Add `DownwardAPILabels` support for `Volume`
  broker/machinebroker/server/machine_create.go
  broker/machinebroker/server/machine_create_test.go
  broker/volumebroker/apiutils/apiutils.go
  broker/volumebroker/cmd/volumebroker/app/app.go
  broker/volumebroker/server/server.go
  broker/volumebroker/server/server_suite_test.go
  broker/volumebroker/server/volume_create.go
  broker/volumebroker/server/volume_create_test.go
  config/volumepoollet-broker/manager/manager.yaml
  poollet/bucketpoollet/controllers/bucket_controller.go
  poollet/bucketpoollet/controllers/bucket_controller_test.go
  poollet/common/utils/utils.go
  poollet/machinepoollet/api/v1alpha1/common_types.go
  poollet/machinepoollet/controllers/machine_controller.go
  poollet/machinepoollet/controllers/machine_controller_test.go
  poollet/volumepoollet/api/v1alpha1/common_types.go
  poollet/volumepoollet/cmd/volumepoollet/app/app.go
  poollet/volumepoollet/controllers/volume_controller.go
  poollet/volumepoollet/controllers/volume_controller_test.go
  poollet/volumepoollet/vem/vem_suite_test.go
  poollet/volumepoollet/vem/vem_test.go
Labels: enhancement, size/L, area/iaas

#1328 Update `MachineRuntime` to reflect `Machine` stopped
  Makefile
  iri/apis/machine/v1alpha1/api.pb.go
  iri/apis/machine/v1alpha1/api.proto
Labels: size/S

#1330 Fix sporadic test failures in `machinepoollet` test suite
  poollet/machinepoollet/controllers/machine_controller_test.go
  poollet/machinepoollet/controllers/machinepool_controller_test.go
  poollet/machinepoollet/mem/mem_test.go
  utils/quota/quota.go
Labels: bug, size/M, area/iaas

#1336 Remove redundant `VirtualIP` test case
  internal/controllers/networking/networkinterface_ephemeralvirtualip_controller_test.go
Labels: bug, size/M, area/iaas

#802 Add proposal for `VolumeSnapshot` resource
  docs/proposals/11-volumesnapshots.md
Labels: documentation, enhancement, size/L, area/iaas

#1346 Introduce separate flags for NIC resource to support `DownwardAPILabels` propagation
  config/machinepoollet-broker/manager/manager.yaml
  poollet/machinepoollet/cmd/machinepoollet/app/app.go
  poollet/machinepoollet/controllers/controllers_suite_test.go
  poollet/machinepoollet/controllers/machine_controller.go
  poollet/machinepoollet/controllers/machine_controller_networkinterface.go
  poollet/machinepoollet/controllers/machine_controller_test.go
  poollet/machinepoollet/mem/mem_test.go
Labels: enhancement, size/M, area/iaas
