Repository ironcore-dev/ironcore, pull requests merged in 2025-05, with the labels that each got.

#1289 Extend `VolumeStatus` to persist lower layer `VolumeID`
  api/storage/v1alpha1/volume_types.go
  client-go/applyconfigurations/internal/internal.go
  client-go/applyconfigurations/storage/v1alpha1/volumestatus.go
  client-go/openapi/zz_generated.openapi.go
  internal/apis/storage/v1alpha1/zz_generated.conversion.go
  internal/apis/storage/volume_types.go
  iri/apis/volume/v1alpha1/api.pb.go
  iri/apis/volume/v1alpha1/api.proto
  iri/apis/volume/v1alpha1/api_grpc.pb.go
  iri/apis/volume/volume.go
  iri/remote/volume/runtime.go
  iri/testing/volume/fake.go
  poollet/machinepoollet/controllers/machine_controller.go
  poollet/machinepoollet/controllers/machine_controller_test.go
  poollet/volumepoollet/cmd/volumepoollet/app/app.go
  poollet/volumepoollet/controllers/controllers_suite_test.go
  poollet/volumepoollet/controllers/volume_controller.go
  poollet/volumepoollet/controllers/volume_controller_test.go
  poollet/volumepoollet/vem/vem_test.go
  utils/poollet/provider_id.go
Labels: enhancement, api-change, size/L

#1290 Remove deprecated reviewers from dependabot configuration
  .github/dependabot.yml
Labels: chore, size/S

#1291 Extend `BucketStatus` to persist lower layer `bucketID`
  api/storage/v1alpha1/bucket_types.go
  client-go/applyconfigurations/internal/internal.go
  client-go/applyconfigurations/storage/v1alpha1/bucketstatus.go
  client-go/openapi/zz_generated.openapi.go
  internal/apis/storage/bucket_types.go
  internal/apis/storage/v1alpha1/zz_generated.conversion.go
  iri/apis/bucket/bucket.go
  iri/apis/bucket/v1alpha1/api.pb.go
  iri/apis/bucket/v1alpha1/api.proto
  iri/apis/bucket/v1alpha1/api_grpc.pb.go
  iri/remote/bucket/runtime.go
  iri/testing/bucket/fake.go
  poollet/bucketpoollet/bem/bem_test.go
  poollet/bucketpoollet/cmd/bucketpoollet/app/app.go
  poollet/bucketpoollet/controllers/bucket_controller.go
  poollet/bucketpoollet/controllers/bucket_controller_test.go
  poollet/bucketpoollet/controllers/controllers_suite_test.go
Labels: enhancement, size/L
